GET http://192.168.1.27/ledState

###
POST http://192.168.1.27/button

###
PUT  http://192.168.1.27/button/set HTTP/1.1
host: 192.168.1.27
accept: application/json
content-type: application/json

{
    "state": "on"
}

###
PUT http://192.168.1.27/button/set?state=on

###
PUT http://192.168.1.27/button/set?state=off

