GET http://192.168.1.27/ledState

###
POST http://192.168.1.27/ledToggle

###
PUT  http://192.168.1.27/ledSet HTTP/1.1
host: 192.168.1.27
accept: application/json
content-type: application/json

{
    "state": "on"
}

###
PUT http://192.168.1.27/ledSet?state=on

###
PUT http://192.168.1.27/ledSet?state=off

