GET http://192.168.1.27/ledState

###
POST http://192.168.1.27/ledToggle

### ne marche pas
PUT  /ledSet HTTP/1.1
Host: 192.168.1.27
Content-Type: application/json
Accept: application/json
Connection: close
Content-Length: 15

{"state":"off"}

###
PUT http://192.168.1.27/ledSet?state=on

###
PUT http://192.168.1.27/ledSet?state=off

###
PUT /ledSet HTTP/1.1
Host: 192.168.1.27
Content-Type: application/x-www-form-urlencoded

state=off

###
PUT /ledSet HTTP/1.1
Host: 192.168.1.27
Content-Type: application/x-www-form-urlencoded

state=on